### ISSUE TITLE
Xcode 9 - "Task" error

### ISSUE THREAD

**Issue by Samigos** [BoltsFramework/Bolts-Swift#63]
I just upgraded Xcode, now with Swift 4 and an error has occurred at the `Task` swift file! See picture below:

<img width="1431" alt="screenshot at sep 23 15-09-58" src="https://user-images.githubusercontent.com/9467442/30775225-6a094de0-a098-11e7-9173-2a3c441c3e6c.png">

It seems the ` success ` case needs an argument...
Have in mind I already have upgraded the SDK with cocoapods.

Thanks in advance!

**Comment by akwilliamson** [comment]
This has been fixed in the pull request I submitted yesterday. Hopefully it gets merged. Until then, change `.success()` to `.success(())` by added empty parentheses

**Edit**: Swift 4 changes have been merged.

**Comment by josmanperez** [comment]
Hi! I'm using the latest release (1.3.0) and I'm still seeing that error. 
Plus in the same file there is two warnings **When calling this function in Swift 4 or later, you must pass a '()' tuple; did you mean for the input type to be '()'?** and one error, but the error goes away when you fix the warning.

You've said that the changes have been merged but the latest release doesn't said anything about Swift 4 changes. 

Thank you!

**Comment by akwilliamson** [comment]
That's because the podspec hasn't been updated to 1.4.0 yet since this repo doesn't seem to be well-looked-after. I posted an issue about it 3 weeks ago [here](https://github.com/BoltsFramework/Bolts-Swift/issues/66). Until that happens you'll need to explicitly point to the repo in your Podfile.

**Comment by josmanperez** [comment]
Thank you so much @akwilliamson :)

**Comment by marchy** [comment]
@akwilliamson mind including how to point to the explicit repo for it?

**Comment by Tudmotu** [comment]
I think this is it @marchy:
https://guides.cocoapods.org/using/the-podfile.html#from-a-podspec-in-the-root-of-a-library-repo

Basically you should put this in your ``Podfile``:
```ruby
pod 'Bolts-Swift', :git => 'https://github.com/BoltsFramework/Bolts-Swift'
```

**Comment by marchy** [comment]
Fantastic, thanks for that @tudmotu :)

**Comment by CiraciNicolo** [comment]
I'm using this project via ParseLiveQuery and I'm still having this issue. It seems that the wrong commit is pulled.

**Comment by carnivash** [comment]
I am also using via ParseLiveQuery and the problem persists, i managed to fix the first error using the above suggestion:
change this: return Task<Void>(state: .success())
to this: return Task<Void>(state: .success(()))

but just below there is another problem on the line:

self.trySet(state: TaskState.fromClosure(closure))

Cannot convert value of type '(Void) throws -> TResult' to expected argument type '() throws -> 

Is there any suggestion to fix this? Thanks.

**Comment by sjmerel** [comment]
I had to do this:
```pod 'Bolts-Swift', :git => 'https://github.com/BoltsFramework/Bolts-Swift', :commit => 'e9baa72d04521c3b25ef4fa6fef12b340953ee02'```

**Comment by rscodra** [comment]
Issue still persists, if the above solutions are not followed.

**Comment by jeffreyjackson** [comment]
thanks @sjmerel your specific commit worked for me too.

**Comment by Verma-Mayank** [comment]
Still having this issue. Tried all of the above.
